language: groovy
dist: xenial
sudo: false
jdk:
- openjdk8

branches:
  only:
  - master

before_install:
- wget -q https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/ala_common.sh
- chmod +x ala_common.sh
- source ./ala_common.sh

- ala_travis_grails_setup_env

script:
- ala_travis_grails_build

env:
  global:
  - secure: m9On1bh5H9vMcRWtUOB/bgSHgQv5w9UueFvL55p00tf1egkm7vtNuQkc6kkbQ5BJMuVc6onw2ZIQbEv8DsXnmwSnQsL3K/PP0QjeHLD+ndl086yespoSC6Hl7l6zhJ380TQM0GWweXQWDIx+MS2V+zqVTOyB4chv8cWGwn47Fc8=
  - secure: nBNRpXDLfLTmuJFSQzH411C1r8wCLGCssOgMzxLVQpb9HWNiVrEm+BI26/sqlMSCrWcZfnOEfKldwztUV5xd816H8r0R4PN63+oIzlrAKBnfIzc99euFPt3Me2kCoNE/VxqSv07Ij7jhoqAAaIJTp/LiLFLGqoL5uuUc6Uql8n0=
